export const usersData = [
    {
        id: 1,
        name: "Aditya Hariharno",
        email: "aditya@example.com",
        phone: "9898989898",
        role: "Admin",
        status: "Pending",
        verified: true,
        isEnabled: false,
        avatar: "https://i.pravatar.cc/150?img=1",
        createdAt: "2025-01-10",
    },
    {
        id: 2,
        name: "Rohit Sharma",
        email: "rohit@example.com",
        phone: "9876543210",
        role: "User",
        status: "Active",
        verified: false,
        isEnabled: true,
        avatar: "https://i.pravatar.cc/150?img=2",
        createdAt: "2025-01-08",
    },
    {
        id: 3,
        name: "Sneha Verma",
        email: "sneha@example.com",
        phone: "9123456789",
        role: "Manager",
        status: "Active",
        verified: true,
        isEnabled: true,
        avatar: "https://i.pravatar.cc/150?img=3",
        createdAt: "2025-01-05",
    },
    {
        id: 4,
        name: "Amit Patel",
        email: "amit@example.com",
        phone: "9988776655",
        role: "User",
        status: "Blocked",
        verified: false,
        isEnabled: false,
        avatar: "https://i.pravatar.cc/150?img=4",
        createdAt: "2024-12-28",
    },
    {
        id: 5,
        name: "Neha Singh",
        email: "neha@example.com",
        phone: "9012345678",
        role: "Admin",
        status: "Active",
        verified: true,
        isEnabled: true,
        avatar: "https://i.pravatar.cc/150?img=5",
        createdAt: "2024-12-20",
    },
];
