export const categoryData = [
    {
        id: "1",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?1",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "2",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?2",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
    {
        id: "3",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?3",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "4",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?4",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
        {
        id: "5",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?5",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
        {
        id: "6",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?6",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "7",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?7",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
    {
        id: "8",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?8",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "9",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?9",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
        {
        id: "10",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?10",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
        {
        id: "11",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?11",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "12",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?12",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
    {
        id: "13",
        product: "iPhone 14 Pro",
        image: "https://picsum.photos/40?13",
        category: "Electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "14",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?14",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
        {
        id: "15",
        product: "Nike Airforce Jordan",
        image: "https://picsum.photos/40?15",
        category: "Footwear",
        createdAt: "2026-01-28",
    },
];
