export const categoryData = [
    {
        id: "1",
        name: "Electronics",
        image: "https://picsum.photos/40?electronics",
        createdAt: "2026-01-28",
    },
    {
        id: "2",
        name: "Footwear",
        image: "https://picsum.photos/40?footwear",
        createdAt: "2026-01-28",
    },
    {
        id: "3",
        name: "Fashion",
        image: "https://picsum.photos/40?fashion",
        createdAt: "2026-01-28",
    },
    {
        id: "4",
        name: "Grocery",
        image: "https://picsum.photos/40?grocery",
        createdAt: "2026-01-28",
    },
    {
        id: "5",
        name: "Home Appliances",
        image: "https://picsum.photos/40?appliances",
        createdAt: "2026-01-28",
    },
    {
        id: "6",
        name: "Furniture",
        image: "https://picsum.photos/40?furniture",
        createdAt: "2026-01-28",
    },
    {
        id: "7",
        name: "Books",
        image: "https://picsum.photos/40?books",
        createdAt: "2026-01-28",
    },
    {
        id: "8",
        name: "Stationery",
        image: "https://picsum.photos/40?stationery",
        createdAt: "2026-01-28",
    },
    {
        id: "9",
        name: "Beauty & Personal Care",
        image: "https://picsum.photos/40?beauty",
        createdAt: "2026-01-28",
    },
    {
        id: "10",
        name: "Health & Wellness",
        image: "https://picsum.photos/40?health",
        createdAt: "2026-01-28",
    },
    {
        id: "11",
        name: "Sports & Fitness",
        image: "https://picsum.photos/40?sports",
        createdAt: "2026-01-28",
    },
    {
        id: "12",
        name: "Toys & Games",
        image: "https://picsum.photos/40?toys",
        createdAt: "2026-01-28",
    },
    {
        id: "13",
        name: "Automotive",
        image: "https://picsum.photos/40?automotive",
        createdAt: "2026-01-28",
    },
    {
        id: "14",
        name: "Mobile Accessories",
        image: "https://picsum.photos/40?mobile",
        createdAt: "2026-01-28",
    },
    {
        id: "15",
        name: "Computer Accessories",
        image: "https://picsum.photos/40?computer",
        createdAt: "2026-01-28",
    },
    {
        id: "16",
        name: "Kitchenware",
        image: "https://picsum.photos/40?kitchen",
        createdAt: "2026-01-28",
    },
    {
        id: "17",
        name: "Lighting",
        image: "https://picsum.photos/40?lighting",
        createdAt: "2026-01-28",
    },
    {
        id: "18",
        name: "Gardening",
        image: "https://picsum.photos/40?gardening",
        createdAt: "2026-01-28",
    },
    {
        id: "19",
        name: "Pet Supplies",
        image: "https://picsum.photos/40?pets",
        createdAt: "2026-01-28",
    },
    {
        id: "20",
        name: "Baby Products",
        image: "https://picsum.photos/40?baby",
        createdAt: "2026-01-28",
    },
    {
        id: "21",
        name: "Office Supplies",
        image: "https://picsum.photos/40?office",
        createdAt: "2026-01-28",
    },
    {
        id: "22",
        name: "Music Instruments",
        image: "https://picsum.photos/40?music",
        createdAt: "2026-01-28",
    },
    {
        id: "23",
        name: "Travel & Luggage",
        image: "https://picsum.photos/40?travel",
        createdAt: "2026-01-28",
    },
    {
        id: "24",
        name: "Jewelry",
        image: "https://picsum.photos/40?jewelry",
        createdAt: "2026-01-28",
    },
    {
        id: "25",
        name: "Watches",
        image: "https://picsum.photos/40?watches",
        createdAt: "2026-01-28",
    },
    {
        id: "26",
        name: "Gaming",
        image: "https://picsum.photos/40?gaming",
        createdAt: "2026-01-28",
    },
    {
        id: "27",
        name: "Smart Home",
        image: "https://picsum.photos/40?smarthome",
        createdAt: "2026-01-28",
    },
    {
        id: "28",
        name: "Cleaning Supplies",
        image: "https://picsum.photos/40?cleaning",
        createdAt: "2026-01-28",
    },
    {
        id: "29",
        name: "Construction Tools",
        image: "https://picsum.photos/40?tools",
        createdAt: "2026-01-28",
    },
    {
        id: "30",
        name: "Medical Equipment",
        image: "https://picsum.photos/40?medical",
        createdAt: "2026-01-28",
    },
];
