export const productsData = [
    {
        id: "p1",
        name: "Apple iPhone 14",
        image: "https://picsum.photos/40?1",
        category: "Electronics",
        brand: "Apple",
        price: 999,
        stock: "In Stock",
        createdAt: "2024-01-01",
    },
    {
        id: "p2",
        name: "Samsung Galaxy S23",
        image: "https://picsum.photos/40?2",
        category: "Electronics",
        brand: "Samsung",
        price: 899,
        stock: "In Stock",
        createdAt: "2024-01-02",
    },
    {
        id: "p3",
        name: "Nike Air Max",
        image: "https://picsum.photos/40?3",
        category: "Footwear",
        brand: "Nike",
        price: 199,
        stock: "Out of Stock",
        createdAt: "2024-01-03",
    },
    {
        id: "p4",
        name: "Adidas Ultraboost",
        image: "https://picsum.photos/40?4",
        category: "Footwear",
        brand: "Adidas",
        price: 180,
        stock: "In Stock",
        createdAt: "2024-01-04",
    },
    {
        id: "p5",
        name: "Sony WH-1000XM5",
        image: "https://picsum.photos/40?5",
        category: "Accessories",
        brand: "Sony",
        price: 349,
        stock: "In Stock",
        createdAt: "2024-01-05",
    },
    {
        id: "p6",
        name: "Dell XPS 13",
        image: "https://picsum.photos/40?6",
        category: "Laptops",
        brand: "Dell",
        price: 1299,
        stock: "Out of Stock",
        createdAt: "2024-01-06",
    },
    {
        id: "p7",
        name: "MacBook Air M2",
        image: "https://picsum.photos/40?7",
        category: "Laptops",
        brand: "Apple",
        price: 1499,
        stock: "In Stock",
        createdAt: "2024-01-07",
    },
    {
        id: "p8",
        name: "Logitech MX Master 3",
        image: "https://picsum.photos/40?8",
        category: "Accessories",
        brand: "Logitech",
        price: 99,
        stock: "In Stock",
        createdAt: "2024-01-08",
    },
    {
        id: "p9",
        name: "Apple Watch Series 9",
        image: "https://picsum.photos/40?9",
        category: "Wearables",
        brand: "Apple",
        price: 399,
        stock: "Out of Stock",
        createdAt: "2024-01-09",
    },
    {
        id: "p10",
        name: "Canon EOS R50",
        image: "https://picsum.photos/40?10",
        category: "Cameras",
        brand: "Canon",
        price: 799,
        stock: "In Stock",
        createdAt: "2024-01-10",
    },

    // 10 more
    {
        id: "p11",
        name: "GoPro Hero 12",
        image: "https://picsum.photos/40?11",
        category: "Cameras",
        brand: "GoPro",
        price: 499,
        stock: "In Stock",
        createdAt: "2024-01-11",
    },
    {
        id: "p12",
        name: "HP Pavilion 15",
        image: "https://picsum.photos/40?12",
        category: "Laptops",
        brand: "HP",
        price: 899,
        stock: "Out of Stock",
        createdAt: "2024-01-12",
    },
    {
        id: "p13",
        name: "Asus ROG Mouse",
        image: "https://picsum.photos/40?13",
        category: "Accessories",
        brand: "Asus",
        price: 79,
        stock: "In Stock",
        createdAt: "2024-01-13",
    },
    {
        id: "p14",
        name: "iPad Pro 11”",
        image: "https://picsum.photos/40?14",
        category: "Tablets",
        brand: "Apple",
        price: 1099,
        stock: "In Stock",
        createdAt: "2024-01-14",
    },
    {
        id: "p15",
        name: "JBL Flip 6",
        image: "https://picsum.photos/40?15",
        category: "Audio",
        brand: "JBL",
        price: 129,
        stock: "Out of Stock",
        createdAt: "2024-01-15",
    },
    {
        id: "p16",
        name: "Samsung Smart TV",
        image: "https://picsum.photos/40?16",
        category: "Electronics",
        brand: "Samsung",
        price: 1599,
        stock: "In Stock",
        createdAt: "2024-01-16",
    },
    {
        id: "p17",
        name: "Mi Band 8",
        image: "https://picsum.photos/40?17",
        category: "Wearables",
        brand: "Xiaomi",
        price: 59,
        stock: "In Stock",
        createdAt: "2024-01-17",
    },
    {
        id: "p18",
        name: "Lenovo ThinkPad X1",
        image: "https://picsum.photos/40?18",
        category: "Laptops",
        brand: "Lenovo",
        price: 1399,
        stock: "Out of Stock",
        createdAt: "2024-01-18",
    },
    {
        id: "p19",
        name: "Bose QC Earbuds",
        image: "https://picsum.photos/40?19",
        category: "Audio",
        brand: "Bose",
        price: 279,
        stock: "In Stock",
        createdAt: "2024-01-19",
    },
    {
        id: "p20",
        name: "Amazon Echo Dot",
        image: "https://picsum.photos/40?20",
        category: "Smart Home",
        brand: "Amazon",
        price: 49,
        stock: "In Stock",
        createdAt: "2024-01-20",
    },
    {
        id: "p22",
        name: "Amazon Echo Dot",
        image: "https://picsum.photos/40?20",
        category: "Smart Home",
        brand: "Amazon",
        price: 49,
        stock: "In Stock",
        createdAt: "2024-01-20",
    },
    {
        id: "p22",
        name: "Amazon Echo Dot",
        image: "https://picsum.photos/40?20",
        category: "Smart Home",
        brand: "Amazon",
        price: 49,
        stock: "In Stock",
        createdAt: "2024-01-20",
    },
];
